[package]
name = "fig"
version = "0.1.0"
authors = ["jesskfulwood <jesskfulwood@gmail.com>"]
edition = "2018"

[dependencies]
derive_more = "0.14.0"
wasm-bindgen = "0.2.37"
js-sys = "0.3.14"
console_error_panic_hook = "0.1.6"
serde = "1.0.89"
wasm-bindgen-futures = "0.3.14"
serde_json = "1.0.39"
futures = "0.1.25"
url = "1.7.2"

[dependencies.web-sys]
version = "0.3.14"
features = [
  'console',
  'AbortController',
  'AbortSignal',
  'Attr',
  'Document',
  'Element',
  'Event',
  'EventTarget',
  'FetchEvent',
  'Headers',
  'History',
  'HtmlAnchorElement',
  'HtmlCollection',
  'HtmlDivElement',
  'HtmlElement',
  'HtmlInputElement',
  'HtmlSelectElement',
  'HtmlTextAreaElement',
  'InputEvent',
  'Location',
  'Node',
  'NodeList',
  'ReferrerPolicy',
  'Request',
  'RequestInit',
  'RequestCache',
  'RequestCredentials',
  'RequestMode',
  'RequestRedirect',
  'Response',
  'Storage',
  'Text',
  'Window',
]
